name: Check Style

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  lint:
    name: Lint

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: webiny/action-conventional-commits@v1.3.0

      - uses: psf/black@stable

      - name: flake8 Lint
        uses: py-actions/flake8@v2
