name: Check Style

on:
  pull_request:
  push:
    branches:
      - master
  workflow_call:

jobs:
  lint:
    name: Lint

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: webiny/action-conventional-commits@v1.3.0

      # Use the minimum supported version for linting
      - name: Set up Python 3.9
        uses: actions/setup-python@v6
        with:
          python-version: "3.9"

      - name: Install poetry
        uses: abatilo/actions-poetry@v4

      - name: Install dependencies
        run: poetry install --with ci

      - name: Check formatting with black
        run: poetry run black --check .

      - name: flake8 Lint
        run: poetry run flake8 ./example_project ./rest_email_auth ./*.py
