name: Publish

on:
  push:
    tags:
      - v*

jobs:
  lint:
    uses: "./.github/workflows/check-style.yml"

  tests:
    uses: "./.github/workflows/run-tests.yml"

  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest

    needs:
      - lint
      - tests

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install poetry
        uses: abatilo/actions-poetry@v2

      - name: Publish package
        run: poetry publish --build
        env:
          POETRY_PYPI_TOKEN_PYPI: "${{ secrets.PYPI_API_TOKEN }}"
