name: Review Build

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  test:
    name: Test

    runs-on: ubuntu-latest
    strategy:
      matrix:
        django-version:
          - '>= 1.11, < 1.12'
          - '>= 2.0, < 2.1'
          - '>= 2.1, < 2.2'
        python-version:
          - "3.6"
          - "3.7"

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install "Django ${{ matrix.django-version }}"
          python setup.py install
          pip install -r requirements/test.txt
          pip install -r requirements/ci.txt

      - name: Check style
        run: |
          black --check .
          flake8

      - name: Test
        run: |
          ./example_project/manage.py check
          coverage run -m pytest

      - name: Upload coverage report
        uses: codecov/codecov-action@v1
