name: Review Build

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  test:
    name: Test

    runs-on: ubuntu-latest
    strategy:
      matrix:
        django-version:
          - '>= 2.2, < 2.3'
          - '>= 3.0, < 3.1'
          - '>= 3.1, < 3.2'
        python-version:
          - "3.6"
          - "3.7"
          - "3.8"
          - "3.9"

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install "Django ${{ matrix.django-version }}"
          python setup.py install
          pip install -r requirements/test.txt
          pip install -r requirements/ci.txt

      - name: Check style
        run: |
          black --check .
          flake8

      - name: Test
        run: |
          ./example_project/manage.py check
          coverage run -m pytest

      - name: Upload coverage report
        uses: codecov/codecov-action@v1

  deploy:
    # Only run on new tags
    if: startsWith(github.ref, 'refs/tags/v')

    # Deployment is predicated on the tests passing.
    needs:
      - test

    name: Deploy to PyPI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Build package
        run: python setup.py sdist bdist_wheel

      - name: Publish to PyPI
        # Version 1.4.1
        uses: pypa/gh-action-pypi-publish@54b39fb9371c0b3a6f9f14bb8a67394defc7a806
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
