name: Run Tests

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  test:
    name: Test

    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          # Django 3.2
          - django-version: '>= 3.2, < 3.3'
            python-version: "3.7"
          - django-version: '>= 3.2, < 3.3'
            python-version: "3.8"
          - django-version: '>= 3.2, < 3.3'
            python-version: "3.9"
          - django-version: '>= 3.2, < 3.3'
            python-version: "3.10"

          # Django 4.0 - 4.1
          - django-version: '>= 4.0, < 4.2'
            python-version: "3.8"
          - django-version: '>= 4.0, < 4.2'
            python-version: "3.9"
          - django-version: '>= 4.0, < 4.2'
            python-version: "3.10"

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4.5.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install poetry
        uses: abatilo/actions-poetry@v2

      - name: Install dependencies
        run: |
          poetry install --with ci
          poetry run pip install "Django ${{ matrix.django-version }}"

      - name: Test
        run: |
          poetry run ./example_project/manage.py check
          poetry run pytest --cov=rest_email_auth

      - name: Upload coverage report
        uses: codecov/codecov-action@v3

  deploy:
    # Only run on new tags
    if: startsWith(github.ref, 'refs/tags/v')

    # Deployment is predicated on the tests passing.
    needs:
      - test

    name: Deploy to PyPI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: "3.9"

      - name: Install packaging dependencies
        run: pip install setuptools wheel

      - name: Build package
        run: python setup.py sdist bdist_wheel

      - name: Publish to PyPI
        # Version 1.4.1
        uses: pypa/gh-action-pypi-publish@54b39fb9371c0b3a6f9f14bb8a67394defc7a806
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
